services:
  - type: web
    name: rando-video-chat
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
